export const TEAM = [
  {
    id: "1",
    name: "Сергей",
    surname: "Егоров",
    githubLogin: "Yogurt7v",
    age: 37,
    done: [
      "Main page",
      "Personal page",
      "Favorite page",
      "Barge",
      "Slider",
      "LocalStorage",
      "Button",
      "Person card",
      "Header",
      "Footer",
    ],
    description: "Team 2 hackathon 2",
    skills: {
      Html: 90,
      Css: 70,
      Js: 85,
      React: 80,
      Redux: 70,
    },
    socialNetwork: {
      vk: "недоступен",
      facebook: "недоступен",
      instagram: "недоступен",
      linkedIn: "недоступен",
      github: "https://github.com/Yogurt7v",
    },
    special: ["teamLead", "frontend"],
    image:
      "https://wdfiles.ru/plugins/imageviewer/site/thumb.php?s=28v89&/Image1.jpg",
  },
  {
    id: "2",
    name: "Александр",
    surname: "Шульгин",
    githubLogin: "Holyhelper1",
    age: 32,
    done: [
      "Main page",
      "Personal page",
      "Favorite page",
      "Barge",
      "Slider",
      "LocalStorage",
      "Button",
      "Person card",
      "Header",
      "Footer",
    ],
    description:
      "Team 2 ackathon 2. Веду активный образ жизни,  решил сменить рабочую профессию и обучаюсь в Result School на Front-end-React разработчика. Люблю путешествовать, узнавать новое, создавать и делать полезные вещи и дела 🙂",
    skills: {
      Html: 90,
      Css: 70,
      Js: 85,
      React: 80,
      Redux: 70,
    },
    socialNetwork: {
      vk: "https://vk.com/alexdude",
      facebook: "https://www.facebook.com/profile.php?id=100002948432331",
      instagram: "https://www.instagram.com/alex_shul_/",
      linkedIn: "https://www.linkedin.com/in/alexander-shulgin-964b49267/",
      github: "https://github.com/Holyhelper1",
    },
    special: ["frontend"],
    image:
      "https://sun9-5.userapi.com/impg/XgW2ssX-L5NRdg9RVFTKGxxKdUXbIMKz5CpuWg/Hw9xx80-0xw.jpg?size=1620x2160&quality=96&sign=72646e592faa0b975137acc425ffbbc1&type=album",
  },
  {
    id: "3",
    name: "Анастасия",
    surname: "Ибрагимова",
    githubLogin: "IbragimovaN",
    age: 29,
    done: [
      "Main page",
      "Personal page",
      "Favorite page",
      "Barge",
      "Slider",
      "LocalStorage",
      "Button",
      "Person card",
      "Header",
      "Footer",
    ],
    description: "Team 2 hackathon 2",
    skills: {
      Html: 90,
      Css: 70,
      Js: 85,
      React: 80,
      Redux: 70,
    },
    socialNetwork: {
      vk: "ibragimova1",
      facebook: "недоступен",
      instagram: "ibragimova.anastasiya",
      linkedIn: "недоступен",
      github: "https://github.com/IbragimovaN",
    },
    special: ["frontend"],
    image:
      "https://static.tildacdn.com/tild3538-3637-4166-b865-346166353965/16768_original.jpg",
  },
  {
    id: "4",
    name: "Роман",
    surname: "Трошин",
    githubLogin: "Roman-Troshin",
    age: 27,
    done: [
      "Main page",
      "Personal page",
      "Favorite page",
      "Barge",
      "Slider",
      "LocalStorage",
      "Button",
      "Person card",
      "Header",
      "Footer",
    ],
    description:
      "Team 2 hackathon 2 Люблю изучать новое, читать научную литературу, интересуюсь музыкой и футболом, мечтаю стать фронтенд-разработчиком",
    skills: {
      Html: 90,
      Css: 70,
      Js: 85,
      React: 80,
      Redux: 70,
    },
    socialNetwork: {
      vk: "https://vk.com/id8516634",
      facebook: "-",
      instagram: "-",
      linkedIn: "-",
      github: "https://github.com/Roman-Troshin",
    },
    special: ["frontend"],
    image: "https://i.postimg.cc/Rh8xSLsK/e2637197-5fb5-44ce-b302-69a5325e.jpg",
  },
];
